### ISSUE TITLE
start_dir_pattern error

### ISSUE THREAD

**Issue by LespiletteMaxime** [erichard/SublimePHPCompanion#29]
Hello,

I get my project in /home/maxime/sites/ when i import namespace it return 

**namespace home/maxime/sites/project**

so I tried to configure *start_dir_pattern* 

I used : 

**"start_dir_pattern" : "home/maxime/sites/"**

and i get this error :

**Traceback (most recent call last):
  File "/home/maxime/bin/SB3/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/home/maxime/.config/sublime-text-3/Packages/PHP Companion/php_companion/commands/import_namespace_command.py", line 25, in run
    namespaceStmt = re.sub(pattern, '\\1', namespaceStmt)
  File "./re.py", line 170, in sub
  File "./re.py", line 311, in filter
  File "./sre_parse.py", line 870, in expand_template
sre_constants.error: invalid group reference**

**Comment by erichard** [comment]
The `start_dir_pattern` must be a valid regex. By default the namespace start at the first CamelCased folded.
