### ISSUE TITLE
AttributeError error on ST3+Windows 7

### ISSUE THREAD

**Issue by cmpex** [erichard/SublimePHPCompanion#36]
Been experiencing an issue on Windows 7.  Thought it was my local Sublime Text so I tested it on a fresh install of Sublime with no other packages installed.

Installation was done using package control and I am running ST3 portable.

Here's the error I'm seeing with every command:
```
Traceback (most recent call last):
  File "F:\dev\sublimetext\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "php_companion.commands.find_use_command in F:\dev\sublimetext\Data\Installed Packages\PHP Companion.sublime-package", line 17, in run
  File "php_companion.utils in F:\dev\sublimetext\Data\Installed Packages\PHP Companion.sublime-package", line 39, in find_symbol
  File "php_companion.settings in F:\dev\sublimetext\Data\Installed Packages\PHP Companion.sublime-package", line 7, in get_setting
AttributeError: 'NoneType' object has no attribute 'get'
```

Wondering if this is something specific to my local ST3 that can be fixed?

Thanks in advance!

**Comment by erichard** [comment]
Can you upgrade the package and tell me if the problem is gone ?

**Comment by cmpex** [comment]
Thanks! I think that did it. Do not see the AttributeError anymore.

However, seeing another error when I try to use the insert constructor property function.  Will create another issue since it's separate.
