### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by umpirsky** [erichard/SublimePHPCompanion#44]
Ubuntu 14.04.2 LTS, Sublime 3, build 3083.

I installed the package, confgured shortcuts:

```
    { "keys": ["f6"], "command": "expand_fqcn" },
    { "keys": ["shift+f6"], "command": "expand_fqcn", "args": {"leading_separator": true} },
    { "keys": ["f5"], "command": "find_use" },
    { "keys": ["f4"], "command": "import_namespace" },
    { "keys": ["shift+f12"], "command": "goto_definition_scope" },
    { "keys": ["f7"], "command": "insert_constructor_prop" }
```

However, it does not react on f4, f5. Simply nothing happens.

I can provide any additional info required for debugging on request.

**Comment by erichard** [comment]
Some basic checks first.

 1. Do you hit F4 in an open php file ?
 2. Do you hit F5 when the cursor is hover a classname and after the project index is fully loaded ?

**Comment by cmpex** [comment]
Open the console: Ctrl-`

Or View > Show Console

Then try to hit any of the keys.  At least, it should be logging some errors.

Otherwise, those keybindings may not be working correctly.

**Comment by cmpex** [comment]
Oh also, the constructor prop command should be:

```
insert_php_constructor_property
```

Instead of:

```
insert_constructor_prop
```

**Comment by erichard** [comment]
Without reproductible steps I can't really help you and you haven't answers my questions.

**Comment by cmpex** [comment]
@erichard Speaking of which, the default keymapping sample file should be updated since the command name changed.

**Comment by umpirsky** [comment]
Thanks for fast response.

> Do you hit F4 in an open php file ?
> Do you hit F5 when the cursor is hover a classname and after the project index is fully loaded ?

@erichard Yes.

@cmpex No errors in console when I run F4 or F5, but I noticed that file is being changed on F4, but no visible changes. 

Here is my console output:

```
DPI scale: 2
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/umpirsky/.config/sublime-text-3/Packages
state path: /home/umpirsky/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/umpirsky/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage", "GitHubinator"]
Unable to decode Packages/Theme - Default.arrow_right.png
pre session restore time: 0.174767
startup time: 0.323187
first paint time: 0.343658
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin All Autocomplete.all_views_completions
reloading plugin DocBlockr.jsdocs
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin PHP Companion.PHP Companion
reloading plugin PHP Getters and Setters.php-getter-setter
['/home/umpirsky/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0', '/opt/sublime_text', '/opt/sublime_text/python3.3.zip', '/home/umpirsky/.config/sublime-text-3/Packages', '/home/umpirsky/.config/sublime-text-3/Packages/bz2/st3_linux_x64']
reloading plugin PHP Getters and Setters.user_templates
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin Package Syncing.Package Syncing
reloading plugin Pman.pman
reloading plugin SublimeLinter-php.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /home/umpirsky/.config/sublime-text-3/Installed Packages/SublimeLinter-php.sublime-package", line 13, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin WakaTime.WakaTime
plugins loaded
[PHP Getters and Setters] Registered template : 'camelCase'
[PHP Getters and Setters] Registered template : 'camelCaseFluent'
[PHP Getters and Setters] Registered template : 'snakeCase'
[PHP Getters and Setters] Registered template : 'snakeCaseFluent'
[PHP Getters and Setters] ignored type hinting var types ['mixed', 'int', 'integer', 'double', 'float', 'number', 'string', 'boolean', 'bool', 'numeric', 'unknown']
[PHP Getters and Setters] template is  'myTemplate'
[PHP Getters and Setters] register extra user templates ['myTemplate']
[PHP Getters and Setters] ignoring visibility to getters and setters
[PHP Getters and Setters] setterBeforeGetter is False
[PHP Getters and Setters] Registered template : 'myTemplate'
[WakaTime] Initializing WakaTime plugin v4.0.8
reloading Packages/User/Package Syncing.sublime-settings
error: unable to open crawldb (~/.config/sublime-text-3/Index), indexing is unavailable
Package Control: No updated packages
```

Is `error: unable to open crawldb (~/.config/sublime-text-3/Index), indexing is unavailable` related? It happens on startup.

**Comment by erichard** [comment]
The `indexing is unavailable` prevent you to use F5 and F6 keys. You may have a corrupted index, try to delete the `~/.config/sublime-text-3/Index` folder.

The F4 key insert a namespace statement in your file. If you already have one, it replaced it. Maybe that why you don't *see* anything...

**Comment by umpirsky** [comment]
@erichard Recreated index, thanks. Now F4 works, but F5, shift+F12...does not.

**Comment by erichard** [comment]
@umpirsky Does "Goto > Goto Symbol in project..." shows you a symbols list ?

**Comment by umpirsky** [comment]
@erichard Ha, it works now, I executed `Goto > Goto Symbol in project...` and after that F5 works. strange.

Thanks.

**Comment by erichard** [comment]
@umpirsky Seems that ST rebuild your index when you executed `Goto Symbols`. Maybe I can detect that the index is empty or corrupted and log something...

**Comment by umpirsky** [comment]
@erichard Probably. Well, I think it's just my case and problem of the editor itself. I think if the index is corrupt, it should popup or something to let user know. I don't think it's something that should be handled on extension level. Thanks.
