### ISSUE TITLE
Exception thrown when using find_use and expand_fqcn

### ISSUE THREAD

**Issue by bblue** [erichard/SublimePHPCompanion#59]
I am experiencing a bug when I try the `find_use` or `expand_fqcn` command. Not really sure what is going on here, but hopefully someone here can make sense of the console output. Clearly some file is missing, but I cannot say which one.

    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "php_companion.commands.find_use_command in C:\Users\bblue\AppData\Roaming\Sublime Text 3\Installed Packages\PHP Companion.sublime-package", line 17, in run
      File "php_companion.utils in C:\Users\bblue\AppData\Roaming\Sublime Text 3\Installed Packages\PHP Companion.sublime-package", line 40, in find_symbol
      File "php_companion.utils in C:\Users\bblue\AppData\Roaming\Sublime Text 3\Installed Packages\PHP Companion.sublime-package", line 45, in find_in_global_namespace
      File "./subprocess.py", line 576, in check_output
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1118, in _execute_child
    FileNotFoundError: [WinError 2] The system cannot find the file specified

I am successfully using `import_namespace` and `goto_definition_scope`

**Comment by erichard** [comment]
Hi @bblue. I think the plugin can't launch the php executable. Do you have php installed and in your PATH env var ?

**Comment by bblue** [comment]
That was it. Just upgraded to php7 with a new install path, forgot to update. Thanks. Easy fix.
